drop table Person;

create table Person(
    id int generated by default as identity primary key,
    name varchar,
    surname varchar,
    birthdate varchar
);

insert into Person(name, surname, birthdate) values('oldName', 'oldSurname', '1980-11-11')