drop table Person;

create table Person(
    id int generated by default as identity primary key,
    name varchar,
    surname varchar,
    birthdate varchar
);

insert into Person(name, surname, birthdate) values('name', 'surname', '1999-11-11')
